### ISSUE TITLE
No longer works on OpenNMS 30.0.0+ (OpenNMS Plugin API v1.0.0)

### ISSUE THREAD

**Issue by tomehb** [OpenNMS/opennms-pagerduty-plugin#9]
No longer works on OpenNMS 30.0.0+ (OpenNMS Plugin API v1.0.0)

Error executing command: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=opennms-plugins-pagerduty; type=karaf.feature; version="[0.1.3,0.1.3]"; filter:="(&(osgi.identity=opennms-plugins-pagerduty)(type=karaf.feature)(version>=0.1.3)(version<=0.1.3))" [caused by: Unable to resolve opennms-plugins-pagerduty/0.1.3: missing requirement [opennms-plugins-pagerduty/0.1.3] osgi.identity; osgi.identity=org.opennms.plugins.pagerduty-plugin; type=osgi.bundle; version="[0.1.3,0.1.3]"; resolution:=mandatory [caused by: Unable to resolve org.opennms.plugins.pagerduty-plugin/0.1.3: missing requirement [org.opennms.plugins.pagerduty-plugin/0.1.3] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.opennms.integration.api.v1.alarms)(version>=0.5.0)(!(version>=1.0.0)))"]]

**Comment by j-white** [comment]
Yeah, we need to make another release with the new API version. We'll get this sorted.

**Comment by mgob** [comment]
Current commit references API v1.1.0+, that fails on release-30.x, changing that in the pom to 1.0.0 succeeds. Plugin loaded cleanly in 30.0.2.

**Comment by d-sudom** [comment]
Any update as to when the fix for this issue will get committed?  Running opennms-31.0.7 and same problem.

**Comment by ravinald** [comment]
@j-white any updates on getting a new build shipped?

**Comment by bmgante** [comment]
Are there any plans to have this fixed for latest opennms version?

**Comment by bmgante** [comment]
Tried with 33.0.3 and problem persists.

`org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=opennms-plugins-pagerduty; type=karaf.feature; version="[0.1.3,0.1.3]"; filter:="(&(osgi.identity=opennms-plugins-pagerduty)(type=karaf.feature)(version>=0.1.3)(version<=0.1.3))" [caused by: Unable to resolve opennms-plugins-pagerduty/0.1.3: missing requirement [opennms-plugins-pagerduty/0.1.3] osgi.identity; osgi.identity=org.opennms.plugins.pagerduty-plugin; type=osgi.bundle; version="[0.1.3,0.1.3]"; resolution:=mandatory [caused by: Unable to resolve org.opennms.plugins.pagerduty-plugin/0.1.3: missing requirement [org.opennms.plugins.pagerduty-plugin/0.1.3] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.opennms.integration.api.v1.alarms)(version>=0.5.0)(!(version>=1.0.0)))"]]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:433)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:420)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:374)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve opennms-plugins-pagerduty/0.1.3: missing requirement [opennms-plugins-pagerduty/0.1.3] osgi.identity; osgi.identity=org.opennms.plugins.pagerduty-plugin; type=osgi.bundle; version="[0.1.3,0.1.3]"; resolution:=mandatory [caused by: Unable to resolve org.opennms.plugins.pagerduty-plugin/0.1.3: missing requirement [org.opennms.plugins.pagerduty-plugin/0.1.3] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.opennms.integration.api.v1.alarms)(version>=0.5.0)(!(version>=1.0.0)))"]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
	... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.opennms.plugins.pagerduty-plugin/0.1.3: missing requirement [org.opennms.plugins.pagerduty-plugin/0.1.3] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.opennms.integration.api.v1.alarms)(version>=0.5.0)(!(version>=1.0.0)))"
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
	... 13 more`

**Comment by dino2gnt** [comment]
> Are there any plans to have this fixed for latest opennms version?

I wouldn't hold my breath.  Probably safe to consider this plugin abandoned, since it hasn't worked for the last two years.

**Comment by bmgante** [comment]
@mgob any chance you could provide the .kar file you were able to build for v30.x? I am having some troubles compiling it.

```
[ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.3.6:verify (verify) on project pagerduty-karaf-features: Execution verify of goal org.apache.karaf.tooling:karaf-maven-plugin:4.3.6:verify failed: A required class was missing while executing org.apache.karaf.tooling:karaf-maven-plugin:4.3.6:verify: org/apache/karaf/features/internal/service/Deployer$DeployCallback
[ERROR] -----------------------------------------------------
[ERROR] realm =    extension>org.apache.karaf.tooling:karaf-maven-plugin:4.3.6
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/var/root/.m2/repository/org/apache/karaf/tooling/karaf-maven-plugin/4.3.6/karaf-maven-plugin-4.3.6.jar
[ERROR] urls[1] = file:/var/root/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
...
[ERROR] : org.apache.karaf.features.internal.service.Deployer$DeployCallback
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :pagerduty-karaf-features
```

Thanks

**Comment by dino2gnt** [comment]
Compiling from current master results in a loadable and functional kar-file for Horizon 33 and Meridian 2024.  We need to cut a v0.1.4 release, but otherwise, this plugin works.
